add this will fail

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -8,4 +8,8 @@ jobs:
         run: |
           echo "hello world"
           echo "Using my first job"
+      - name: this will fail
+        run:  |
+          echo "This will fail"
+          exit 1
       
